### ISSUE TITLE
Got error message with slack bot

### ISSUE THREAD

**Issue by mrnonz** [binary-com/gce-manager#7]
I got this message `INFO - Connection to Slack failed, invalid token?`

but when I am try to use token with cURL this normally.

How to find this bug and fix ?

**Comment by teo-binary** [comment]
That means your slack token is not a valid one.. You will need to create a
chat not token from slack admin portal

**Comment by teo-binary** [comment]
Hi @mrnonz  you will need to create a bot user then obtain the token from there

https://api.slack.com/bot-users
