### ISSUE TITLE
Have problem when my preemptible is going down

### ISSUE THREAD

**Issue by mrnonz** [binary-com/gce-manager#8]
`try exceeded after 2 call(s). Reason: <HttpError 400 when requesting https://www.googleapis.com/compute/v1/projects/...../zones/asia-east1-a/disks?alt=json returned "Invalid value for field 'resource.sourceSnapshot': 'projects/...../global/snapshots/my_snapshot'. The referenced snapshot resource cannot be found.">`

This code show when use about 2-3 recycle (preemptible)  and My instance is vanished.

**Comment by teo-binary** [comment]
Preemptible instance are terminated by Google at random times, but the error shows that your base snapshot image was removed or changed hence it is not able to spawn new preemptible instances from snapshot

**Comment by mrnonz** [comment]
Do you know "How to prevent this issue in future?"

Thank you

**Comment by teo-binary** [comment]
When you replaced your snapshot, you must update the snapshot id in the
config file.

**Comment by mrnonz** [comment]
`GCE_SNAPSHOT_SOURCE: projects/my_project_id/global/snapshots/my_snapshot`

This is you mean?

**Comment by teo-binary** [comment]
Yes
