### ISSUE TITLE
I got Backend Error message

### ISSUE THREAD

**Issue by mrnonz** [binary-com/gce-manager#9]
`[2016-09-15 14:31:10] INFO - list_instance() failed: internal_failure: Backend Error. Retrying...
[2016-09-15 23:28:54] INFO - list_instance() failed: internal_failure: Backend Error. Retrying...`

Here last log in program and that can't restart any instance sine 2016-09-15

How can find to fix this issue?

**Comment by teo-binary** [comment]
Hi, this is an error from Google cloud API. There is no way we can fix that issue. Perhaps you want to file a support ticket to them.

I've seen that error, but it usually happens few times a day intermittently and simply recovers after few minutes.
